## 1. Load data

*No data from xG from before 17-18 season*

Checked that the master is created is there is nothing weird in the columns of both dataframes

In [7]:
import json
import pandas as pd
from pathlib import Path

In [51]:
raw_df=pd.read_json("/Users/rodrigo/Documents/python/champions_league_luck/champions_league_luck/data/combined/combined_all.json")
expected_df=pd.read_json("/Users/rodrigo/Documents/python/champions_league_luck/champions_league_luck/data/combined/combined_expected.json")

In [62]:
raw_df.shape

(328, 17)

In [63]:
expected_df.shape

(586, 9)

In [30]:
df=pd.read_csv("/Users/rodrigo/Documents/python/champions_league_luck/champions_league_luck/data/combined/master.csv")

In [60]:
df.shape

(645, 21)

In [61]:
df_clean = df.dropna(subset=["xg", "shots_on_target"])

## 2. First draft cleaning process

In [64]:
df_luck=pd.read_csv("/Users/rodrigo/Documents/python/champions_league_luck/champions_league_luck/data/combined/master_with_luck.csv")

In [66]:
df_luck[df_luck['team']=='Real Madrid']

,team,season,mp,xg,xga,xgd,goals_scored,goals_conceded,country,squad_size,...,sh_per_90,sot_per_90,g_per_sh,g_per_sot,pk,pk_att,attack_luck,defense_luck,finish_luck,luck_score
212,Real Madrid,17-18,13.0,1.92,1.28,0.64,2.54,1.23,es,23.0,...,17.00,6.54,0.13,0.34,4.0,4.0,0.322917,0.039062,0.192127,0.184702
213,Real Madrid,18-19,8.0,1.96,1.26,0.70,1.88,1.25,es,24.0,...,19.13,7.25,0.10,0.26,0.0,0.0,-0.040816,0.007937,-0.088373,-0.040418
214,Real Madrid,19-20,8.0,2.05,1.38,0.67,2.00,1.50,es,25.0,...,17.25,6.62,0.11,0.28,1.0,1.0,-0.024390,-0.086957,-0.018248,-0.043198
215,Real Madrid,20-21,12.0,1.66,1.11,0.55,1.58,1.17,es,25.0,...,13.42,5.08,0.10,0.26,2.0,2.0,-0.048193,-0.054054,-0.088373,-0.063540
216,Real Madrid,21-22,13.0,1.66,1.74,-0.08,2.23,1.08,es,25.0,...,13.10,4.83,0.14,0.38,3.0,3.0,0.343373,0.379310,0.332377,0.351687
217,Real Madrid,22-23,12.0,1.79,1.34,0.45,2.17,1.08,es,22.0,...,15.33,6.17,0.13,0.31,3.0,3.0,0.212291,0.194030,0.086940,0.164420
218,Real Madrid,23-24,13.0,1.55,1.36,0.19,2.15,1.15,es,23.0,...,15.90,5.40,0.12,0.35,1.0,2.0,0.387097,0.154412,0.227190,0.256233
219,Real Madrid,24-25,14.0,1.68,1.55,0.13,2.07,1.57,es,23.0,...,14.58,5.79,0.13,0.34,1.0,3.0,0.232143,-0.012903,0.192127,0.137122
220,Real Madrid,25-26,14.0,1.93,1.83,0.10,2.36,1.43,es,30.0,...,17.67,6.92,0.11,0.29,4.0,5.0,0.222798,0.218579,0.016814,0.152731

In [67]:
luck_analysis=pd.read_csv("/Users/rodrigo/Documents/python/champions_league_luck/champions_league_luck/data/combined/luck_summary.csv")

In [69]:
luck_analysis[luck_analysis['team']=='Real Madrid']

,team,n_seasons,mean_luck,std_luck,mean_attack_luck,mean_defense_luck,mean_finish_luck,ci_lower,ci_upper,t_stat,p_raw,best_season,worst_season,p_adj,significant
7,Real Madrid,9,0.122193,0.14395,0.17858,0.093268,0.094731,0.035212,0.210036,2.546571,0.034358,21-22,20-21,0.211872,False

-Analyze current results

-Explore the use of more columns

-Analyze the meaning of everything and thi k about writting the Notion page

-Plots look really nice