### Condense all data

*No data from xG from before 17-18 season*

In [7]:
import json
import pandas as pd
from pathlib import Path

In [12]:
raw_df=pd.read_json("/Users/rodrigo/Documents/python/champions_league_luck/champions_league_luck/data/combined/combined_all.json")

In [26]:
df=pd.read_csv("/Users/rodrigo/Documents/python/champions_league_luck/champions_league_luck/data/combined/master.csv")

In [27]:
df.columns

Index(['team', 'season', 'mp', 'xg', 'xga', 'xgd', 'goals_scored',
       'goals_conceded', 'country', 'squad_size', '90s_played', 'gls', 'shots',
       'shots_on_target', 'sot_pct', 'sh_per_90', 'sot_per_90', 'g_per_sh',
       'g_per_sot', 'pk', 'pk_att'],
      dtype='str')

In [ ]:
df = df.dropna(subset=["xg", "shots_on_target"])

,team,season,mp,xg,xga,xgd,goals_scored,goals_conceded,country,squad_size,...,gls,shots,shots_on_target,sot_pct,sh_per_90,sot_per_90,g_per_sh,g_per_sot,pk,pk_att
0,AC Omonia Nicosia,20-21,5.0,1.24,1.84,-0.60,0.80,0.60,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AC Omonia Nicosia,21-22,2.0,1.21,2.08,-0.87,0.00,1.50,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AEK Athens,17-18,2.0,1.69,1.37,0.32,0.00,1.50,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AEK Athens,18-19,10.0,0.85,1.71,-0.86,0.80,1.70,gr,20.0,...,2.0,39.0,9.0,23.1,6.50,1.50,0.05,0.22,0.0,0.0
4,AEK Athens,23-24,4.0,1.89,1.11,0.78,1.25,1.50,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
640,Young Boys,23-24,8.0,1.03,1.70,-0.67,1.25,1.63,ch,23.0,...,6.0,73.0,21.0,28.8,12.17,3.50,0.07,0.24,1.0,1.0
641,Young Boys,24-25,NaN,NaN,NaN,NaN,NaN,NaN,ch,24.0,...,3.0,81.0,18.0,22.2,10.13,2.25,0.04,0.17,0.0,0.0
642,Zenit,19-20,6.0,1.22,2.11,-0.89,1.17,1.50,ru,19.0,...,6.0,59.0,20.0,33.9,9.83,3.33,0.10,0.30,0.0,0.0
643,Zenit,20-21,6.0,1.03,1.59,-0.56,0.67,2.17,ru,21.0,...,3.0,59.0,14.0,23.7,9.83,2.33,0.05,0.21,0.0,0.0
644,Zenit,21-22,6.0,1.50,1.50,0.00,1.67,1.67,ru,21.0,...,9.0,79.0,25.0,31.6,13.17,4.17,0.10,0.32,1.0,1.0

In [18]:
raw_df.columns

Index(['Squad', 'Country', 'Pl', '90s', 'Gls', 'Sh', 'SoT', 'SoT_Pct',
       'Sh_per_90', 'SoT_per_90', 'G_per_Sh', 'G_per_SoT', 'PK', 'PKatt',
       'season'],
      dtype='str')

In [19]:
raw_df.head()

,Squad,Country,Pl,90s,Gls,Sh,SoT,SoT_Pct,Sh_per_90,SoT_per_90,G_per_Sh,G_per_SoT,PK,PKatt,season
0,Arsenal,eng,21,8.0,19,94,42,44.7,11.75,5.25,0.19,0.43,1,2,16-17
1,Atlético Madrid,es,20,12.0,15,158,56,35.4,13.17,4.67,0.08,0.21,3,4,16-17
2,Barcelona,es,23,10.0,25,131,52,39.7,13.10,5.20,0.17,0.42,3,4,16-17
3,Basel,ch,18,6.0,3,63,20,31.7,10.50,3.33,0.05,0.15,0,0,16-17
4,Bayern Munich,de,21,10.3,26,188,74,39.4,18.19,7.16,0.12,0.30,4,5,16-17

In [23]:
raw_df.shape

(328, 15)

In [25]:
raw_df[raw_df['season']=='22-23']

,Squad,Country,Pl,90s,Gls,Sh,SoT,SoT_Pct,Sh_per_90,SoT_per_90,G_per_Sh,G_per_SoT,PK,PKatt,season
192,Ajax,nl,19,6.0,11,64,22,34.4,10.67,3.67,0.16,0.45,1,1,22-23
193,Atlético Madrid,es,22,6.0,4,95,34,35.8,15.83,5.67,0.04,0.12,0,2,22-23
194,Barcelona,es,26,6.0,12,90,33,36.7,15.00,5.50,0.13,0.36,0,0,22-23
195,Bayern Munich,de,24,10.0,21,167,72,43.1,16.70,7.20,0.12,0.28,1,1,22-23
196,Benfica,pt,24,10.0,25,133,48,36.1,13.30,4.80,0.15,0.42,5,5,22-23
197,Celtic,sct,22,6.0,3,82,29,35.4,13.67,4.83,0.04,0.10,0,1,22-23
198,Chelsea,eng,26,10.0,12,152,51,33.6,15.20,5.10,0.07,0.20,2,2,22-23
199,Club Brugge,be,25,8.0,8,67,20,29.9,8.37,2.50,0.10,0.35,1,2,22-23
200,Dinamo Zagreb,hr,20,6.0,4,55,20,36.4,9.17,3.33,0.07,0.20,0,0,22-23
201,Dortmund,de,26,8.0,11,97,27,27.8,12.12,3.38,0.11,0.41,0,0,22-23
202,Eintracht Frankfurt,de,22,8.0,7,75,26,34.7,9.37,3.25,0.08,0.23,1,1,22-23
203,FC Copenhagen,dk,25,6.0,1,54,16,29.6,9.00,2.67,0.02,0.06,0,0,22-23
204,Inter,it,22,13.0,19,166,62,37.3,12.77,4.77,0.11,0.29,1,1,22-23
205,Juventus,it,26,6.0,9,78,25,32.1,13.00,4.17,0.12,0.36,0,0,22-23
206,Leverkusen,de,20,6.0,4,81,27,33.3,13.50,4.50,0.05,0.15,0,2,22-23
207,Liverpool,eng,25,8.0,19,126,55,43.7,15.75,6.87,0.14,0.33,1,1,22-23
208,Maccabi Haifa,il,20,6.0,7,76,21,27.6,12.67,3.50,0.08,0.29,1,1,22-23
209,Manchester City,eng,23,13.0,31,196,85,43.4,15.08,6.54,0.15,0.34,2,5,22-23
210,Marseille,fr,19,6.0,8,79,23,29.1,13.17,3.83,0.09,0.30,1,1,22-23
211,Milan,it,23,12.0,14,135,42,31.1,11.25,3.50,0.09,0.29,2,3,22-23
212,Napoli,it,22,NaN,26,167,63,37.7,16.70,6.30,0.13,0.35,4,8,22-23
213,Paris Saint-Germain,fr,21,8.0,15,99,41,41.4,12.38,5.12,0.14,0.34,1,1,22-23
214,Porto,pt,24,8.0,12,111,38,34.2,13.87,4.75,0.08,0.24,3,3,22-23
215,Rangers,sct,22,6.0,2,43,10,23.3,7.17,1.67,0.02,0.10,1,1,22-23
216,RB Leipzig,de,22,8.0,13,88,34,38.6,11.00,4.25,0.15,0.38,0,0,22-23
217,RB Salzburg,at,19,6.0,5,84,27,32.1,14.00,4.50,0.05,0.15,1,1,22-23
218,Real Madrid,es,22,12.0,26,184,74,40.2,15.33,6.17,0.13,0.31,3,3,22-23
219,Sevilla,es,24,6.0,6,68,24,35.3,11.33,4.00,0.09,0.25,0,0,22-23
220,Shakhtar Donetsk,ua,20,6.0,8,45,15,33.3,7.50,2.50,0.18,0.53,0,0,22-23
221,Sporting CP,pt,25,6.0,8,45,21,46.7,7.50,3.50,0.18,0.38,0,0,22-23
222,Tottenham Hotspur,eng,25,8.0,8,95,29,30.5,11.87,3.62,0.07,0.24,1,2,22-23
223,Viktoria Plzeň,cz,22,6.0,5,67,19,28.4,11.17,3.17,0.06,0.21,1,1,22-23

In [22]:
raw_df[raw_df['Squad']=='Atlético Madrid']

,Squad,Country,Pl,90s,Gls,Sh,SoT,SoT_Pct,Sh_per_90,SoT_per_90,G_per_Sh,G_per_SoT,PK,PKatt,season
1,Atlético Madrid,es,20,12.0,15,158,56,35.4,13.17,4.67,0.08,0.21,3,4,16-17
34,Atlético Madrid,es,20,6.0,5,105,33,31.4,17.50,5.50,0.04,0.12,1,1,17-18
66,Atlético Madrid,es,21,8.0,11,89,30,33.7,11.12,3.75,0.12,0.37,0,0,18-19
98,Atlético Madrid,es,21,9.3,13,119,43,36.1,12.75,4.61,0.09,0.26,2,3,19-20
130,Atlético Madrid,es,20,8.0,7,95,31,32.6,11.87,3.87,0.07,0.23,0,0,20-21
162,Atlético Madrid,es,22,10.0,9,95,25,26.3,9.50,2.50,0.08,0.32,1,1,21-22
193,Atlético Madrid,es,22,6.0,4,95,34,35.8,15.83,5.67,0.04,0.12,0,2,22-23
226,Atlético Madrid,es,22,10.3,20,136,52,38.2,13.16,5.03,0.15,0.38,0,1,23-24
259,Atlético Madrid,es,23,10.3,22,123,48,39.0,11.90,4.65,0.18,0.46,0,0,24-25
296,Atlético Madrid,es,26,12.0,30,181,73,40.3,15.08,6.08,0.15,0.38,2,2,25-26

In [15]:
raw_df['12.0'].value_counts()

12.0
12.0    1
Name: count, dtype: int64

In [4]:
expected.drop(columns=['xG_vs_Actual', 'xG vs Actual'], inplace=True)

In [5]:
expected[expected["Team"]=="SSC Napoli"]

     Rank        Team  MP    xG   xGA   xGD    GF    GA season
8       9  SSC Napoli   8  1.69  1.17  0.52  1.88  1.38  17-18
89     16  SSC Napoli   6  1.54  1.08  0.46  1.17  0.83  18-19
181    38  SSC Napoli   8  1.37  1.46 -0.09  1.63  1.00  19-20
367     3  SSC Napoli  10  1.99  1.16  0.83  2.60  0.80  22-23
488    49  SSC Napoli   8  1.22  1.62 -0.40  1.50  1.63  23-24
579    33  SSC Napoli   8  1.39  1.41 -0.02  1.13  1.88  25-26

In [6]:
expected.to_json("data/combined/combined_expected.json", index=False)

In [ ]:
# Ensure numeric types for calculation
expected['xG'] = pd.to_numeric(expected['xG'], errors='coerce')
expected['GF'] = pd.to_numeric(expected['GF'], errors='coerce')
expected['xG_vs_Actual'] = expected['xG'] - expected['GF']
expected['xGA_vs_Actual'] = expected['xGA'] - expected['GA']

print(expected[['season', 'Team', 'xG', 'GF', 'xG_Difference']])

    season                        Team    xG    GF  xG_Difference
0    17-18           FC Bayern München  2.13  2.17          -0.04
1    17-18             SK Slavia Praha  1.94  0.50           1.44
2    17-18              Real Madrid CF  1.92  2.54          -0.62
3    17-18              BSC Young Boys  1.89  0.75           1.14
4    17-18                Liverpool FC  1.84  3.13          -1.29
..     ...                         ...   ...   ...            ...
581  25-26    BVB 09 Borussia Dortmund  1.37  2.20          -0.83
582  25-26               SK Sturm Graz  1.37  1.00           0.37
583  25-26                FC København  1.35  1.64          -0.29
584  25-26  Royal Union Saint-Gilloise  1.35  1.00           0.35
585  25-26               PSV Eindhoven  1.32  2.00          -0.68

[586 rows x 5 columns]

In [37]:
df_clean = df.dropna(subset=["shots_on_target", "xga"])

In [38]:
df_clean.shape

(269, 22)

In [39]:
df_clean[df_clean["team"]=='Ajax'].head(10)

,team,season,mp,xg,xga,xgd,goals_scored,goals_conceded,xg_vs_actual,country,...,gls,shots,shots_on_target,sot_pct,sh_per_90,sot_per_90,g_per_sh,g_per_sot,pk,pk_att
12,Ajax,18-19,18.0,1.63,1.23,0.40,1.94,0.94,0.31,nl,...,22.0,183.0,68.0,37.2,15.25,5.67,0.11,0.29,2.0,2.0
13,Ajax,19-20,10.0,1.69,1.28,0.41,1.90,1.00,0.21,nl,...,10.0,76.0,24.0,31.6,12.67,4.00,0.13,0.42,0.0,0.0
14,Ajax,20-21,6.0,1.51,1.43,0.08,1.17,1.17,-0.34,nl,...,7.0,69.0,28.0,40.6,11.50,4.67,0.09,0.21,1.0,1.0
15,Ajax,21-22,8.0,2.00,1.06,0.94,2.75,1.00,0.75,nl,...,21.0,128.0,48.0,37.5,16.00,6.00,0.16,0.42,1.0,1.0
16,Ajax,22-23,6.0,1.35,1.68,-0.33,1.83,2.67,NaN,nl,...,11.0,64.0,22.0,34.4,10.67,3.67,0.16,0.45,1.0,1.0

In [31]:
df[['xg_vs_actual', 'country', 'squad_size', '90s_played',
       'gls', 'shots']]

     xg_vs_actual country  squad_size  90s_played  gls  shots
0           -0.44     NaN         NaN         NaN  NaN    NaN
1           -1.21     NaN         NaN         NaN  NaN    NaN
2           -1.69     NaN         NaN         NaN  NaN    NaN
3           -0.05      gr        20.0         6.0  2.0   39.0
4           -0.64     NaN         NaN         NaN  NaN    NaN
..            ...     ...         ...         ...  ...    ...
608          0.22      ch        23.0         6.0  6.0   73.0
609           NaN      ch        24.0         8.0  3.0   81.0
610         -0.05      ru        19.0         6.0  6.0   59.0
611         -0.36      ru        21.0         6.0  3.0   59.0
612          0.17      ru        21.0         6.0  9.0   79.0

[613 rows x 6 columns]

In [10]:
expected.Team.unique()

<StringArray>
[        'FC Bayern München',           'SK Slavia Praha',
            'Real Madrid CF',            'BSC Young Boys',
              'Liverpool FC',   'Club Atlético de Madrid',
    'Paris Saint-Germain FC',                'Sevilla FC',
                'SSC Napoli',             'AEK Athens FC',
 ...
          'Royal Antwerp FC',         'FC Differdange 03',
        'VfB Stuttgart 1893', 'SSA Jagiellonia Białystok',
  'Tic Tapa UE Santa Coloma',            'Aston Villa FC',
      'FK Ordabasy Shymkent',           'FC Dinamo Minsk',
         'Stade Brestois 29',           'KKS Lech Poznań']
Length: 200, dtype: str

In [7]:
expected.columns

Index(['Rank', 'Team', 'MP', 'xG', 'xGA', 'xGD', 'GF', 'GA', 'xG_vs_Actual',
       'season', 'xG vs Actual'],
      dtype='str')

In [4]:
raw.season.value_counts()

season
2024/25    36
2025/26    36
2017/18    32
2018/19    32
2019/20    32
2020/21    32
2021/22    32
2022/23    32
2023/24    32
Name: count, dtype: int64

In [21]:
raw_clean=raw[raw["season"]!="2016/17"]

In [23]:
raw_clean.to_json("data/combined/combined_all.json")

In [22]:
raw_clean.season.value_counts()

season
2024/25    36
2025/26    36
2017/18    32
2018/19    32
2019/20    32
2020/21    32
2021/22    32
2022/23    32
2023/24    32
Name: count, dtype: int64

In [14]:
expected.season.value_counts()

season
20-21    75
22-23    75
17-18    74
21-22    74
19-20    72
18-19    70
23-24    64
24-25    43
25-26    39
Name: count, dtype: int64

In [9]:
expected.to_json("data/combined_expected.json")

In [5]:
df=pd.read_json("/Users/rodrigo/Documents/python/champions_league_luck/champions_league_luck/data/combined/combined_all.json")

In [7]:
df

,Squad,Country,Pl,90s,Gls,Sh,SoT,SoT_Pct,Sh_per_90,SoT_per_90,G_per_Sh,G_per_SoT,PK,PKatt,season,12.0,10.0
0,Arsenal,eng,21,8.0,19,94,42,44.7,11.75,5.25,0.19,0.43,1,2,2016/17,NaN,NaN
1,Atlético Madrid,es,20,12.0,15,158,56,35.4,13.17,4.67,0.08,0.21,3,4,2016/17,NaN,NaN
2,Barcelona,es,23,10.0,25,131,52,39.7,13.10,5.20,0.17,0.42,3,4,2016/17,NaN,NaN
3,Basel,ch,18,6.0,3,63,20,31.7,10.50,3.33,0.05,0.15,0,0,2016/17,NaN,NaN
4,Bayern Munich,de,21,10.3,26,188,74,39.4,18.19,7.16,0.12,0.30,4,5,2016/17,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
323,Slavia Prague,cz,23,8.0,4,99,30,30.3,12.38,3.75,0.04,0.13,0,0,2025/26,NaN,NaN
324,Sporting CP,pt,29,10.3,21,136,55,40.4,13.16,5.32,0.14,0.35,2,3,2025/26,NaN,NaN
325,Tottenham Hotspur,eng,27,10.0,19,129,54,41.9,12.90,5.40,0.12,0.30,3,4,2025/26,NaN,NaN
326,Union SG,be,21,8.0,8,95,39,41.1,11.87,4.87,0.07,0.18,1,1,2025/26,NaN,NaN
327,Villarreal,es,25,8.0,5,109,30,27.5,13.62,3.75,0.05,0.17,0,0,2025/26,NaN,NaN

In [18]:
df.drop(columns=['12.0', '10.0'], inplace=True)

In [21]:
df.shape

(328, 15)

In [23]:
df.columns

Index(['Squad', 'Country', 'Pl', '90s', 'Gls', 'Sh', 'SoT', 'SoT_Pct',
       'Sh_per_90', 'SoT_per_90', 'G_per_Sh', 'G_per_SoT', 'PK', 'PKatt',
       'season'],
      dtype='object')

In [29]:
df_sample = df[df['Squad'].isin(['Barcelona', 'Real Madrid'])]

In [30]:
df_sample

,Squad,Country,Pl,90s,Gls,Sh,SoT,SoT_Pct,Sh_per_90,SoT_per_90,G_per_Sh,G_per_SoT,PK,PKatt,season
2,Barcelona,es,23,10.0,25,131,52,39.7,13.10,5.20,0.17,0.42,3,4,2016/17
27,Real Madrid,es,23,13.3,34,238,93,39.1,17.85,6.98,0.14,0.37,0,0,2016/17
35,Barcelona,es,22,10.0,12,129,53,41.1,12.90,5.30,0.09,0.23,0,0,2017/18
57,Real Madrid,es,23,13.0,33,221,85,38.5,17.00,6.54,0.13,0.34,4,4,2017/18
67,Barcelona,es,23,12.0,25,199,77,38.7,16.58,6.42,0.12,0.31,1,1,2018/19
87,Real Madrid,es,24,8.0,15,153,58,37.9,19.13,7.25,0.10,0.26,0,0,2018/19
99,Barcelona,es,24,9.0,13,103,42,40.8,11.44,4.67,0.12,0.29,1,1,2019/20
121,Real Madrid,es,25,8.0,16,138,53,38.4,17.25,6.62,0.11,0.28,1,1,2019/20
131,Barcelona,es,27,8.0,18,137,55,40.1,17.12,6.87,0.09,0.22,6,7,2020/21
155,Real Madrid,es,25,12.0,18,161,61,37.9,13.42,5.08,0.10,0.26,2,2,2020/21
163,Barcelona,es,23,6.0,2,60,11,18.3,10.00,1.83,0.03,0.18,0,0,2021/22
184,Real Madrid,es,25,13.7,28,179,66,36.9,13.10,4.83,0.14,0.38,3,3,2021/22
194,Barcelona,es,26,6.0,12,90,33,36.7,15.00,5.50,0.13,0.36,0,0,2022/23
218,Real Madrid,es,22,12.0,26,184,74,40.2,15.33,6.17,0.13,0.31,3,3,2022/23
227,Barcelona,es,25,10.0,19,158,55,34.8,15.80,5.50,0.12,0.35,0,0,2023/24
249,Real Madrid,es,23,13.3,26,212,72,34.0,15.90,5.40,0.12,0.35,1,2,2023/24
260,Barcelona,es,27,14.3,40,221,93,42.1,15.42,6.49,0.17,0.40,3,3,2024/25
283,Real Madrid,es,23,14.3,29,209,83,39.7,14.58,5.79,0.13,0.34,1,3,2024/25
297,Barcelona,es,24,10.0,29,167,70,41.9,16.70,7.00,0.15,0.36,4,4,2025/26
322,Real Madrid,es,30,12.0,28,212,83,39.2,17.67,6.92,0.11,0.29,4,5,2025/26

In [26]:
df.Squad.value_counts().head(10)

Squad
Dortmund               10
Real Madrid            10
Manchester City        10
Atlético Madrid        10
Paris Saint-Germain    10
Barcelona              10
Bayern Munich          10
Benfica                 9
Juventus                9
Inter                   8
Name: count, dtype: int64

In [4]:
import json
import pandas as pd
from pathlib import Path

data_dir = Path("data/all")

dfs = []
for path in sorted(data_dir.glob("*.json")):
    if path.stat().st_size == 0:
        continue
    season = path.stem.replace("_", "-")  # "17_18" → "17-18"
    with open(path) as f:
        records = json.load(f)
    df = pd.DataFrame(records)
    df["season"] = season
    dfs.append(df)

combined_all = pd.concat(dfs, ignore_index=True)
print(combined_all.shape)
combined_all.head()

(328, 17)

,Squad,Country,Pl,90s,Gls,Sh,SoT,SoT_Pct,Sh_per_90,SoT_per_90,G_per_Sh,G_per_SoT,PK,PKatt,season,12.0,10.0
0,Arsenal,eng,21,8.0,19,94,42,44.7,11.75,5.25,0.19,0.43,1,2,16-17,NaN,NaN
1,Atlético Madrid,es,20,12.0,15,158,56,35.4,13.17,4.67,0.08,0.21,3,4,16-17,NaN,NaN
2,Barcelona,es,23,10.0,25,131,52,39.7,13.10,5.20,0.17,0.42,3,4,16-17,NaN,NaN
3,Basel,ch,18,6.0,3,63,20,31.7,10.50,3.33,0.05,0.15,0,0,16-17,NaN,NaN
4,Bayern Munich,de,21,10.3,26,188,74,39.4,18.19,7.16,0.12,0.30,4,5,16-17,NaN,NaN

In [5]:
combined_all.to_json("data/combined/combined_all.json", index=False)